export const chineseDecks = [
  {
    name: "Common Daily Phrases",
    description: "Essential Chinese phrases for everyday conversations",
    cards: [
      { front: "Hello", back: "你好 (Nǐ hǎo)" },
      { front: "Goodbye", back: "再见 (Zàijiàn)" },
      { front: "Thank you", back: "谢谢 (Xièxiè)" },
      { front: "You're welcome", back: "不客气 (Bú kèqì)" },
      { front: "Sorry", back: "对不起 (Duìbuqǐ)" },
      { front: "How are you?", back: "你好吗？ (Nǐ hǎo ma?)" },
      { front: "I'm fine", back: "我很好 (Wǒ hěn hǎo)" },
      { front: "What's your name?", back: "你叫什么名字？ (Nǐ jiào shénme míngzì?)" },
      { front: "My name is...", back: "我叫... (Wǒ jiào...)" },
      { front: "Nice to meet you", back: "很高兴认识你 (Hěn gāoxìng rènshi nǐ)" },
      { front: "Yes", back: "是 (Shì)" },
      { front: "No", back: "不是 (Bú shì)" },
      { front: "Please", back: "请 (Qǐng)" },
      { front: "Excuse me", back: "请问 (Qǐngwèn)" },
      { front: "I don't understand", back: "我不明白 (Wǒ bù míngbai)" },
      { front: "Do you speak English?", back: "你会说英语吗？ (Nǐ huì shuō Yīngyǔ ma?)" },
      { front: "How much?", back: "多少钱？ (Duōshao qián?)" },
      { front: "Delicious", back: "好吃 (Hǎochī)" },
      { front: "I love you", back: "我爱你 (Wǒ ài nǐ)" },
      { front: "Cheers", back: "干杯 (Gānbēi)" },
    ],
  },
  {
    name: "Common Verbs",
    description: "Most frequently used Chinese verbs",
    cards: [
      { front: "To go", back: "去 (Qù)" },
      { front: "To come", back: "来 (Lái)" },
      { front: "To eat", back: "吃 (Chī)" },
      { front: "To drink", back: "喝 (Hē)" },
      { front: "To speak", back: "说 (Shuō)" },
      { front: "To see", back: "看 (Kàn)" },
      { front: "To listen", back: "听 (Tīng)" },
      { front: "To read", back: "读 (Dú)" },
      { front: "To write", back: "写 (Xiě)" },
      { front: "To buy", back: "买 (Mǎi)" },
      { front: "To want", back: "要 (Yào)" },
      { front: "To have", back: "有 (Yǒu)" },
      { front: "To be able to", back: "会 (Huì)" },
      { front: "To like", back: "喜欢 (Xǐhuān)" },
      { front: "To know", back: "知道 (Zhīdao)" },
    ],
  },
  {
    name: "Common Words",
    description: "Everyday Chinese vocabulary for beginners",
    cards: [
      { front: "Water", back: "水 (Shuǐ)" },
      { front: "Tea", back: "茶 (Chá)" },
      { front: "Rice", back: "米饭 (Mǐfàn)" },
      { front: "Noodles", back: "面条 (Miàntiáo)" },
      { front: "Friend", back: "朋友 (Péngyou)" },
      { front: "Family", back: "家庭 (Jiātíng)" },
      { front: "Home", back: "家 (Jiā)" },
      { front: "School", back: "学校 (Xuéxiào)" },
      { front: "Book", back: "书 (Shū)" },
      { front: "Money", back: "钱 (Qián)" },
      { front: "Time", back: "时间 (Shíjiān)" },
      { front: "Today", back: "今天 (Jīntiān)" },
      { front: "Tomorrow", back: "明天 (Míngtiān)" },
      { front: "Yesterday", back: "昨天 (Zuótiān)" },
      { front: "Now", back: "现在 (Xiànzài)" },
    ],
  },
];
