export const frenchDecks = [
  {
    name: "Salutations & Phrases de Base",
    description: "Apprenez les salutations et expressions essentielles en français",
    cards: [
      { front: "Hello", back: "Bonjour" },
      { front: "Good evening", back: "Bonsoir" },
      { front: "Goodbye", back: "Au revoir" },
      { front: "See you later", back: "Tout à l'heure" },
      { front: "See you tomorrow", back: "À demain" },
      { front: "Please", back: "S'il vous plaît" },
      { front: "Thank you", back: "Merci" },
      { front: "You're welcome", back: "De rien" },
      { front: "Sorry", back: "Pardon" },
      { front: "Excuse me", back: "Excusez-moi" },
      { front: "How are you?", back: "Comment allez-vous ?" },
      { front: "I'm fine, thank you", back: "Je vais bien, merci" },
      { front: "What is your name?", back: "Comment vous appelez-vous ?" },
      { front: "My name is...", back: "Je m'appelle..." },
      { front: "Nice to meet you", back: "Enchanté" },
      { front: "Yes", back: "Oui" },
      { front: "No", back: "Non" },
      { front: "Maybe", back: "Peut-être" },
      { front: "I don't understand", back: "Je ne comprends pas" },
      { front: "Do you speak English?", back: "Parlez-vous anglais ?" },
    ],
  },
  {
    name: "Nombres & Chiffres",
    description: "Maîtrisez les nombres en français de 1 à 1000",
    cards: [
      { front: "1", back: "Un" },
      { front: "2", back: "Deux" },
      { front: "3", back: "Trois" },
      { front: "4", back: "Quatre" },
      { front: "5", back: "Cinq" },
      { front: "6", back: "Six" },
      { front: "7", back: "Sept" },
      { front: "8", back: "Huit" },
      { front: "9", back: "Neuf" },
      { front: "10", back: "Dix" },
      { front: "11", back: "Onze" },
      { front: "12", back: "Douze" },
      { front: "13", back: "Treize" },
      { front: "14", back: "Quatorze" },
      { front: "15", back: "Quinze" },
      { front: "16", back: "Seize" },
      { front: "17", back: "Dix-sept" },
      { front: "18", back: "Dix-huit" },
      { front: "19", back: "Dix-neuf" },
      { front: "20", back: "Vingt" },
      { front: "30", back: "Trente" },
      { front: "40", back: "Quarante" },
      { front: "50", back: "Cinquante" },
      { front: "100", back: "Cent" },
      { front: "1000", back: "Mille" },
    ],
  },
  {
    name: "Famille & Relations",
    description: "Le vocabulaire de la famille et des relations personnelles",
    cards: [
      { front: "Family", back: "La famille" },
      { front: "Mother", back: "La mère" },
      { front: "Father", back: "Le père" },
      { front: "Sister", back: "La sœur" },
      { front: "Brother", back: "Le frère" },
      { front: "Daughter", back: "La fille" },
      { front: "Son", back: "Le fils" },
      { front: "Wife", back: "La femme" },
      { front: "Husband", back: "Le mari" },
      { front: "Grandmother", back: "La grand-mère" },
      { front: "Grandfather", back: "Le grand-père" },
      { front: "Aunt", back: "La tante" },
      { front: "Uncle", back: "L'oncle" },
      { front: "Cousin (f)", back: "La cousine" },
      { front: "Cousin (m)", back: "Le cousin" },
      { front: "Friend (f)", back: "L'amie" },
      { front: "Friend (m)", back: "L'ami" },
      { front: "Baby", back: "Le bébé" },
      { front: "Child", back: "L'enfant" },
      { front: "Neighbor", back: "Le voisin / La voisine" },
    ],
  },
  {
    name: "Verbes Essentiels",
    description: "Les verbes les plus importants pour communiquer en français",
    cards: [
      { front: "To be", back: "Être" },
      { front: "To have", back: "Avoir" },
      { front: "To do / To make", back: "Faire" },
      { front: "To go", back: "Aller" },
      { front: "To say / To tell", back: "Dire" },
      { front: "To know", back: "Savoir" },
      { front: "To can / To be able to", back: "Pouvoir" },
      { front: "To must / To have to", back: "Devoir" },
      { front: "To want", back: "Vouloir" },
      { front: "To come", back: "Venir" },
      { front: "To see", back: "Voir" },
      { front: "To take", back: "Prendre" },
      { front: "To give", back: "Donner" },
      { front: "To speak", back: "Parler" },
      { front: "To eat", back: "Manger" },
      { front: "To drink", back: "Boire" },
      { front: "To read", back: "Lire" },
      { front: "To write", back: "Écrire" },
      { front: "To understand", back: "Comprendre" },
      { front: "To learn", back: "Apprendre" },
    ],
  },
  {
    name: "Nourriture & Boissons",
    description: "Le vocabulaire essentiel pour manger et boire en France",
    cards: [
      { front: "Water", back: "L'eau" },
      { front: "Coffee", back: "Le café" },
      { front: "Tea", back: "Le thé" },
      { front: "Milk", back: "Le lait" },
      { front: "Juice", back: "Le jus" },
      { front: "Wine", back: "Le vin" },
      { front: "Beer", back: "La bière" },
      { front: "Bread", back: "Le pain" },
      { front: "Butter", back: "Le beurre" },
      { front: "Cheese", back: "Le fromage" },
      { front: "Egg", back: "L'œuf" },
      { front: "Meat", back: "La viande" },
      { front: "Chicken", back: "Le poulet" },
      { front: "Fish", back: "Le poisson" },
      { front: "Vegetable", back: "Le légume" },
      { front: "Fruit", back: "Le fruit" },
      { front: "Rice", back: "Le riz" },
      { front: "Sugar", back: "Le sucre" },
      { front: "Salt", back: "Le sel" },
      { front: "The meal", back: "Le repas" },
    ],
  },
  {
    name: "Voyage & Transport",
    description: "Vocabulaire utile pour voyager dans les pays francophones",
    cards: [
      { front: "Airport", back: "L'aéroport" },
      { front: "Train station", back: "La gare" },
      { front: "Bus stop", back: "L'arrêt de bus" },
      { front: "Ticket", back: "Le billet" },
      { front: "Passport", back: "Le passeport" },
      { front: "Hotel", back: "L'hôtel" },
      { front: "Room", back: "La chambre" },
      { front: "Reservation", back: "La réservation" },
      { front: "Map", back: "La carte" },
      { front: "Suitcase", back: "La valise" },
      { front: "Beach", back: "La plage" },
      { front: "Museum", back: "Le musée" },
      { front: "Restaurant", back: "Le restaurant" },
      { front: "Shop", back: "Le magasin" },
      { front: "Hospital", back: "L'hôpital" },
      { front: "Pharmacy", back: "La pharmacie" },
      { front: "Bank", back: "La banque" },
      { front: "Post office", back: "La poste" },
      { front: "Left", back: "À gauche" },
      { front: "Right", back: "À droite" },
    ],
  },
  {
    name: "Temps & Saisons",
    description: "Le vocabulaire du temps, des jours, des mois et des saisons",
    cards: [
      { front: "Monday", back: "Lundi" },
      { front: "Tuesday", back: "Mardi" },
      { front: "Wednesday", back: "Mercredi" },
      { front: "Thursday", back: "Jeudi" },
      { front: "Friday", back: "Vendredi" },
      { front: "Saturday", back: "Samedi" },
      { front: "Sunday", back: "Dimanche" },
      { front: "January", back: "Janvier" },
      { front: "February", back: "Février" },
      { front: "March", back: "Mars" },
      { front: "April", back: "Avril" },
      { front: "May", back: "Mai" },
      { front: "June", back: "Juin" },
      { front: "July", back: "Juillet" },
      { front: "August", back: "Août" },
      { front: "September", back: "Septembre" },
      { front: "October", back: "Octobre" },
      { front: "November", back: "Novembre" },
      { front: "December", back: "Décembre" },
      { front: "Today", back: "Aujourd'hui" },
      { front: "Yesterday", back: "Hier" },
      { front: "Tomorrow", back: "Demain" },
      { front: "Spring", back: "Le printemps" },
      { front: "Summer", back: "L'été" },
      { front: "Autumn / Fall", back: "L'automne" },
      { front: "Winter", back: "L'hiver" },
      { front: "Morning", back: "Le matin" },
      { front: "Afternoon", back: "L'après-midi" },
      { front: "Evening", back: "Le soir" },
      { front: "Night", back: "La nuit" },
    ],
  },
  {
    name: "Couleurs & Adjectifs",
    description: "Apprenez les couleurs et les adjectifs courants en français",
    cards: [
      { front: "Red", back: "Rouge" },
      { front: "Blue", back: "Bleu" },
      { front: "Green", back: "Vert" },
      { front: "Yellow", back: "Jaune" },
      { front: "White", back: "Blanc" },
      { front: "Black", back: "Noir" },
      { front: "Orange", back: "Orange" },
      { front: "Pink", back: "Rose" },
      { front: "Purple", back: "Violet" },
      { front: "Gray", back: "Gris" },
      { front: "Brown", back: "Marron" },
      { front: "Big", back: "Grand" },
      { front: "Small", back: "Petit" },
      { front: "Hot", back: "Chaud" },
      { front: "Cold", back: "Froid" },
      { front: "Good", back: "Bon" },
      { front: "Bad", back: "Mauvais" },
      { front: "New", back: "Nouveau" },
      { front: "Old", back: "Vieux" },
      { front: "Beautiful", back: "Beau" },
    ],
  },
  {
    name: "Assurance Maladie Vocabulaire",
    description: "Vocabulaire essentiel pour naviguer le système de santé français",
    cards: [
      { front: "Health insurance", back: "L'assurance maladie" },
      { front: "Social Security", back: "La Sécurité Sociale" },
      { front: "Mutual insurance company", back: "La mutuelle" },
      { front: "Health Insurance Fund", back: "La Caisse d'Assurance Maladie (CPAM)" },
      { front: "General practitioner", back: "Le médecin traitant" },
      { front: "Specialist", back: "Le spécialiste" },
      { front: "Appointment", back: "Le rendez-vous" },
      { front: "Prescription", back: "L'ordonnance" },
      { front: "Reimbursement", back: "Le remboursement" },
      { front: "100% coverage", back: "Le tiers payant" },
      { front: "Treatment", back: "Le traitement" },
      { front: "Hospital", back: "L'hôpital" },
      { front: "Emergency room", back: "Les urgences" },
      { front: "Surgery", back: "La chirurgie" },
      { front: "Vaccination", back: "La vaccination" },
      { front: "Sick leave", back: "L'arrêt maladie" },
      { front: "Health record", back: "Le dossier médical" },
      { front: "Vital card", back: "La carte Vitale" },
      { front: "European Health Insurance Card", back: "La carte européenne d'assurance maladie (CEAM)" },
      { front: "Certificate of hospitalization", back: "Le bulletin d'hospitalisation" },
      { front: "Medical imaging", back: "L'imagerie médicale" },
      { front: "Blood test", back: "La prise de sang" },
      { front: "Doctor's fee", back: "Le tarif de consultation" },
      { front: "Approved rate", back: "Le tarif de convention" },
      { front: "Excess fee", back: "Le dépassement d'honoraires" },
    ],
  },
  {
    name: "Verbes au Présent",
    description: "Conjugaison des verbes essentiels au présent de l'indicatif",
    cards: [
      { front: "Je (être)", back: "Je suis" },
      { front: "Tu (être)", back: "Tu es" },
      { front: "Il/Elle (être)", back: "Il/elle est" },
      { front: "Nous (être)", back: "Nous sommes" },
      { front: "Vous (être)", back: "Vous êtes" },
      { front: "Ils/Elles (être)", back: "Ils/elles sont" },
      { front: "Je (avoir)", back: "J'ai" },
      { front: "Tu (avoir)", back: "Tu as" },
      { front: "Il/Elle (avoir)", back: "Il/elle a" },
      { front: "Nous (avoir)", back: "Nous avons" },
      { front: "Vous (avoir)", back: "Vous avez" },
      { front: "Ils/Elles (avoir)", back: "Ils/elles ont" },
      { front: "Je (aller)", back: "Je vais" },
      { front: "Tu (aller)", back: "Tu vas" },
      { front: "Il/Elle (aller)", back: "Il/elle va" },
      { front: "Nous (aller)", back: "Nous allons" },
      { front: "Vous (aller)", back: "Vous allez" },
      { front: "Ils/Elles (aller)", back: "Ils/elles vont" },
      { front: "Je (faire)", back: "Je fais" },
      { front: "Tu (faire)", back: "Tu fais" },
      { front: "Il/Elle (faire)", back: "Il/elle fait" },
      { front: "Nous (faire)", back: "Nous faisons" },
      { front: "Vous (faire)", back: "Vous faites" },
      { front: "Ils/Elles (faire)", back: "Ils/elles font" },
      { front: "Je (pouvoir)", back: "Je peux" },
      { front: "Tu (pouvoir)", back: "Tu peux" },
      { front: "Il/Elle (pouvoir)", back: "Il/elle peut" },
      { front: "Nous (pouvoir)", back: "Nous pouvons" },
      { front: "Vous (pouvoir)", back: "Vous pouvez" },
      { front: "Ils/Elles (pouvoir)", back: "Ils/elles peuvent" },
    ],
  },
];
