export const japaneseDecks = [
  {
    name: "Common Daily Phrases",
    description: "Essential Japanese phrases for everyday conversations",
    cards: [
      { front: "Hello", back: "こんにちは (Konnichiwa)" },
      { front: "Good morning", back: "おはようございます (Ohayou gozaimasu)" },
      { front: "Good evening", back: "こんばんは (Konbanwa)" },
      { front: "Goodbye", back: "さようなら (Sayounara)" },
      { front: "See you later", back: "また後で (Mata ato de)" },
      { front: "Thank you", back: "ありがとうございます (Arigatou gozaimasu)" },
      { front: "You're welcome", back: "どういたしまして (Dou itashimashite)" },
      { front: "Sorry", back: "ごめんなさい (Gomen nasai)" },
      { front: "Excuse me", back: "すみません (Sumimasen)" },
      { front: "How are you?", back: "お元気ですか (Ogenki desu ka)" },
      { front: "I'm fine", back: "元気です (Genki desu)" },
      { front: "What's your name?", back: "お名前は何ですか (Onamae wa nan desu ka)" },
      { front: "My name is...", back: "私の名前は...です (Watashi no namae wa... desu)" },
      { front: "Nice to meet you", back: "はじめまして (Hajimemashite)" },
      { front: "Yes", back: "はい (Hai)" },
      { front: "No", back: "いいえ (Iie)" },
      { front: "Please", back: "お願いします (Onegai shimasu)" },
      { front: "I don't understand", back: "わかりません (Wakarimasen)" },
      { front: "Do you speak English?", back: "英語を話せますか (Eigo o hanasemasu ka)" },
      { front: "I love you", back: "愛しています (Aishite imasu)" },
    ],
  },
  {
    name: "Common Verbs",
    description: "Most frequently used Japanese verbs",
    cards: [
      { front: "To go", back: "行く (Iku)" },
      { front: "To come", back: "来る (Kuru)" },
      { front: "To eat", back: "食べる (Taberu)" },
      { front: "To drink", back: "飲む (Nomu)" },
      { front: "To speak", back: "話す (Hanasu)" },
      { front: "To see", back: "見る (Miru)" },
      { front: "To listen", back: "聞く (Kiku)" },
      { front: "To read", back: "読む (Yomu)" },
      { front: "To write", back: "書く (Kaku)" },
      { front: "To buy", back: "買う (Kau)" },
      { front: "To do", back: "する (Suru)" },
      { front: "To meet", back: "会う (Au)" },
      { front: "To sleep", back: "寝る (Neru)" },
      { front: "To think", back: "思う (Omou)" },
      { front: "To understand", back: "分かる (Wakaru)" },
    ],
  },
  {
    name: "Common Words",
    description: "Everyday Japanese vocabulary for beginners",
    cards: [
      { front: "Water", back: "水 (Mizu)" },
      { front: "Tea", back: "お茶 (Ocha)" },
      { front: "Rice", back: "ご飯 (Gohan)" },
      { front: "Friend", back: "友達 (Tomodachi)" },
      { front: "Family", back: "家族 (Kazoku)" },
      { front: "Home", back: "家 (Ie)" },
      { front: "School", back: "学校 (Gakkou)" },
      { front: "Book", back: "本 (Hon)" },
      { front: "Money", back: "お金 (Okane)" },
      { front: "Time", back: "時間 (Jikan)" },
      { front: "Today", back: "今日 (Kyou)" },
      { front: "Tomorrow", back: "明日 (Ashita)" },
      { front: "Yesterday", back: "昨日 (Kinou)" },
      { front: "Now", back: "今 (Ima)" },
      { front: "Weather", back: "天気 (Tenki)" },
    ],
  },
];
