export const spanishDecks = [
  {
    name: "Common Daily Phrases",
    description: "Essential Spanish phrases for everyday conversations",
    cards: [
      { front: "Hello", back: "Hola" },
      { front: "Good morning", back: "Buenos días" },
      { front: "Good afternoon", back: "Buenas tardes" },
      { front: "Good night", back: "Buenas noches" },
      { front: "Goodbye", back: "Adiós" },
      { front: "See you later", back: "Hasta luego" },
      { front: "Thank you", back: "Gracias" },
      { front: "You're welcome", back: "De nada" },
      { front: "Please", back: "Por favor" },
      { front: "Sorry", back: "Lo siento" },
      { front: "How are you?", back: "¿Cómo estás?" },
      { front: "I'm fine", back: "Estoy bien" },
      { front: "What's your name?", back: "¿Cómo te llamas?" },
      { front: "My name is...", back: "Me llamo..." },
      { front: "Nice to meet you", back: "Mucho gusto" },
      { front: "Yes", back: "Sí" },
      { front: "No", back: "No" },
      { front: "I don't understand", back: "No entiendo" },
      { front: "Do you speak English?", back: "¿Hablas inglés?" },
      { front: "How much?", back: "¿Cuánto cuesta?" },
    ],
  },
  {
    name: "Common Verbs",
    description: "Most frequently used Spanish verbs",
    cards: [
      { front: "To be (permanent)", back: "Ser" },
      { front: "To be (temporary)", back: "Estar" },
      { front: "To have", back: "Tener" },
      { front: "To do / To make", back: "Hacer" },
      { front: "To go", back: "Ir" },
      { front: "To say / To tell", back: "Decir" },
      { front: "To can / To be able to", back: "Poder" },
      { front: "To want", back: "Querer" },
      { front: "To know (facts)", back: "Saber" },
      { front: "To know (people)", back: "Conocer" },
      { front: "To come", back: "Venir" },
      { front: "To see", back: "Ver" },
      { front: "To eat", back: "Comer" },
      { front: "To drink", back: "Beber" },
      { front: "To speak", back: "Hablar" },
      { front: "To read", back: "Leer" },
      { front: "To write", back: "Escribir" },
      { front: "To understand", back: "Comprender" },
      { front: "To buy", back: "Comprar" },
      { front: "To work", back: "Trabajar" },
    ],
  },
  {
    name: "Common Words",
    description: "Everyday Spanish vocabulary for beginners",
    cards: [
      { front: "Water", back: "Agua" },
      { front: "Food", back: "Comida" },
      { front: "Friend", back: "Amigo" },
      { front: "Family", back: "Familia" },
      { front: "House", back: "Casa" },
      { front: "School", back: "Escuela" },
      { front: "Book", back: "Libro" },
      { front: "Money", back: "Dinero" },
      { front: "Time", back: "Tiempo" },
      { front: "Day", back: "Día" },
      { front: "Night", back: "Noche" },
      { front: "Love", back: "Amor" },
      { front: "Beautiful", back: "Hermoso" },
      { front: "Big", back: "Grande" },
      { front: "Small", back: "Pequeño" },
    ],
  },
];
